In [37]:
#Find the shape 
import numpy as np
b = np.array([10, 20, 30, 40, 50, 60, 70])
print(b.shape)
#find the number od dimentions
print(b.ndim)
# find the number od elements 
print(b.size)

# find the max and min and sum and mean of this aray
c = np.array([-10, 201, 43, 94, 502])

print(c.min() , c.max(), int(c.mean()), c.sum())
#add these two arays 
v = np.array([0, 1])
u = np.array([1, 0])

z = np.add(u, v)
z
#do it again
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
sumarr1and2 = np.add(arr1, arr2)
print(sumarr1and2)

#subtract
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
a=np.subtract(arr1,arr2)
print(a)
#multiply
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])
edsheran = np.multiply(arr1, arr2)
print(edsheran)
#devide
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
allOfEdSherensAlbumbs = np.divide(arr1, arr2)
print(allOfEdSherensAlbumbs)
#dot the two matrecys, i mean arrays.

arr1 = np.array([3, 5])
arr2 = np.array([2, 4])
print(np.dot(arr1, arr2))

#append 5 
arr = np.array([1, 2, 3, -1]) 
arr = arr+ 5
print(arr)


#using linspace Make a numpy array within [5, 4] and 6 elements
print(np.linspace(5,4,num = 6))


#use vector subtractions
u = np.array([1, 0])
v = np.array([0, 1])
lol = u-v 

#Multiply the numpy array z with -2:
z = np.array([2, 4])
print(np.multiply(z, -2))
#Consider the list [1, 2, 3, 4, 5] and [1, 0, 1, 0, 1]. Cast both lists to a numpy array then multiply them together:
a=np.array([1, 2, 3, 4, 5])
b=np.array ([1, 0, 1, 0, 1])
print(np.multiply(a,b))

(7,)
1
7
-10 502 166 830
[30 32 34 36 38 40]
[-10  -1   8  17  26  35]
[ 20  20  60 120 200 300]
[ 3.33333333  4.          3.          5.         25.          1.81818182]
26
[6 7 8 4]
[5.  4.8 4.6 4.4 4.2 4. ]


In [12]:
#the two colapsed things are code that they gave me
import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
def Plotvec2(a,b):
    ax = plt.axes()# to generate the full window axes
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)#Add an arrow to the  a Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)#Add an arrow to the  b Axes with arrow head width 0.05, color blue and arrow head length 0.1
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)


#Convert the list [-1, 1] and [1, 1] to numpy arrays a and b. Then, plot the arrays as vectors using the fuction Plotvec2 and find their dot product:

a=np.array([-1,1])
b = np.array([1,1])

Plotvec2(a,b)

np.dot(a,b)
#ran into an error trying to get it to graph
#Convert the list [1, 0] and [0, 1] to numpy arrays a and b. Then, plot the arrays as vectors using the function Plotvec2 and find their dot product:

a2 = np.array([1,0])
b2 = np.array([0,2])

np.dot(a2,b2)
#Still geting the graphing error AttributeError: module 'matplotlib' has no attribute 'get_data_path' there is also another one but there seems to be a problem with there function. 








AttributeError: module 'matplotlib' has no attribute 'get_data_path'

In [15]:

#Convert the list [1, 2, 3] and [8, 9, 10] to numpy arrays arr1 and arr2. Then perform Addition , Subtraction , Multiplication ,
# Division and Dot Operation on the arr1 and arr2.

arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

added = np.add(arr1, arr2)
print(added)

subed = np.subtract(arr1, arr2)
print(subed)

edsheran = np.multiply(arr1, arr2)
print(edsheran)


TheOtherEdSheranAlbumb= np.divide(arr1, arr2)
print(TheOtherEdSheranAlbumb, "i actuly like this one more")

Dotthei = np.dot(arr1, arr2)
print(Dotthei)




[ 9 11 13]
[-7 -7 -7]
[ 8 18 30]
[0.125      0.22222222 0.3       ] i actuly like this one more
56


In [22]:
#Convert the list [1, 2, 3, 4, 5] and [6, 7, 8, 9, 10] to numpy arrays arr1 and arr2. Then find the even and odd numbers from arr1 and arr2.

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

def odd(arr):
    i = 0
    odds = []
    even = []
    for i in arr:
        #we can do the below cus there will be a remander of one for the odd ones and that == true in computer lengo 
        if i % 2:
            odds.append(i)
        else:
            even.append(i)

    return("odds:", odds, "evens", even)
print("for arr1",odd(arr1))
print("for arr2",odd(arr2))

for arr1 ('odds:', [1, 3, 5], 'evens', [2, 4])
for arr2 ('odds:', [7, 9], 'evens', [6, 8, 10])
